application:
  features:
    support: true
    support-pagerduty: true

azure:
  resourcegroup:
    tags:
      - name: Foo
        label: Barfoo
        placeholder: Description here
        type: input
        default: foobar

kubernetes:
  roleBinding:
    annotations:
      foo: annotation
    labels:
      bar: label

  namespace:
    settings:
      - name: foobar
        k8stype: label
        k8sname: example.com/foobar-l
        label: Foobar
        type: input
        validation:
          regexp: "^.+$"
      - name: barfoo
        k8stype: annotation
        k8sname: janitor/ttl
        label: Auto delete
        description: TTL until namespace is deleted (eg. 6h, 7d, 31d, 2w)
        type: input
        default: "31d"
        validation:
          regexp: "^[0-9]+[hdw]$"
          required: true
      - name: servicemesh
        k8stype: annotation
        k8sname: istio-injection
        label: Enable ServiceMesh
        type: checkbox
        default: "true"
        k8svalue: "enabled"
      - name: barfoo1
        type: hidden
        k8stype: annotation
        k8sname: static-annotation
        k8svalue: "foobar1"
      - name: barfoo2
        type: hidden
        k8stype: label
        k8sname: static-label
        k8svalue: "foobar2"


permissions:
  adminGroups: [01fab9bf-e71e-42e0-b936-0f90c5616e7c]
  teams:
    01fab9bf-e71e-42e0-b936-0f90c5616e7c:
      name: admin
      azure:
        group: 01fab9bf-e71e-42e0-b936-0f90c5616e7c
        servicePrincipal: 827dc3a3-ae49-4a5a-b632-28ad35079d7e


    995031e1-ede7-4162-91b8-c68bdc44e955:
      name: devopsteam1
      azure:
        group: 995031e1-ede7-4162-91b8-c68bdc44e955

    e1a8deaf-58d1-4bbe-a80c-3cb34d72da98:
      name: devopsteam2
      azure:
        group: e1a8deaf-58d1-4bbe-a80c-3cb34d72da98

