application:
  features:
    kubernetes: true
    kubernetes-namespaces: true
    kubernetes-access: true

    azure: true
    azure-resourcegroups: true
    azure-roleassignments: true

    monitoring: true
    monitoring-alertmanagers: true

    general: true
    general-settings: true
    general-about: true


  session:
    type: {{env "SESSION_TYPE" | default "internal" | toJson }}
    expiry: {{env "SESSION_EXPIRY" | default "168h" | toJson }}

    cookieName: {{env "SESSION_COOKIE_NAME" | default "devconsole-sid" | toJson }}
    cookieSecure: {{env "SESSION_COOKIE_SECURE" | default "true" }}
    cookieDomain: {{env "SESSION_COOKIE_DOMAIN" | default "" | toJson }}

    internal: {}

    secureCookie:
      hashKey: {{env "SESSION_SECURECOOKIE_HASHKEY" | default "F11JJT1PWFfcPbcnltjMeiFSEZOt3F3I" | toJson }}
      blockKey: {{env "SESSION_SECURECOOKIE_BLOCKKEY" | default "XDC0RgG55pPRQLb!" | toJson }}

    redis:
      addr: {{env "SESSION_REDIS_ADDR" | toJson }}
      timeout: {{env "SESSION_REDIS_TIMEOUT"  | default "10s" | toJson }}
      maxActive: {{env "SESSION_REDIS_MAXACTIVE"  | default "10" | int }}
      password: {{env "SESSION_REDIS_PASSWORD"  | default "" | toJson }}
      database: {{env "SESSION_REDIS_DATABASE"  | default "" | toJson }}
      prefix: {{env "SESSION_REDIS_PREFIX"  | default "" | toJson }}
      delim:  {{env "SESSION_REDIS_DELIM"  | default "|" | toJson }}

  oauth:
    provider: {{env "OAUTH_PROVIDER" | toJson }}
    usernamePrefix: {{env "OAUTH_USERNAME_PREFIX" | toJson }}
    groupPrefix: {{env "OAUTH_GROUPS_PREFIX" | default ""  | toJson }}
    redirectUrl: {{env "OAUTH_REDIRECT_URL" | default "" | toJson }}

    azuread:
      tenant: {{env "OAUTH_AZUREAD_TENANT" | toJson }}
      clientId: {{env "OAUTH_CLIENT_ID" | toJson }}
      clientSecret: {{env "OAUTH_CLIENT_SECRET" | toJson }}

      endpointAuth: {{env "OAUTH_ENDPOINT_AUTH" | toJson }}
      endpointToken: {{env "OAUTH_ENDPOINT_TOKEN" | toJson }}

    filter:
      usernameWhitelist: {{env "OAUTH_USERNAME_FILTER_WHITELIST" | toJson }}
      usernameBlacklist: {{env "OAUTH_USERNAME_FILTER_BLACKLIST" | toJson }}

  notification:
    channels: {{ env "NOTIFICATION_CHANNELS" | splitList " " | toJson }}
    message: {{env "NOTIFICATION_MESSAGE" | default "%s: %s" | toJson }}

settings:
  vault:
    url: {{env "AZURE_VAULT_URL" | toJson }}

  user: []
  team: []

azure:
  roleassignment:
    roledefinitions:
      - Owner
      - Contributor
      - Reader
    ttl:
      - 1h
      - 2h
      - 4h
      - 8h

  resourcegroup:
    validation:
      regexp: "^(.+)-rg$"

    tags: []


kubernetes:
  objectsPath: ./config/kubernetes

  roleBinding:
    annotations: {}
    labels: {}

  environments: []

  namespace:
    filter:
      access: {{env "K8S_NAMESPACE_ACCESS_FILTER" | default "^(dev|test|int|isa|load|play|prod|team|user)\\-([a-zA-Z0-9]+\\-[a-zA-Z0-9]+|[a-zA-Z0-9]+)$" | toJson }}
      delete: {{env "K8S_NAMESPACE_DELETE_FILTER" | default "^(team|user)\\-.*$" | toJson }}
      user: {{env "K8S_NAMESPACE_USER_FILTER" | default "^user\\-%s\\-" | toJson }}
      team: {{env "K8S_NAMESPACE_TEAM_FILTER" | default "^team\\-%s\\-" | toJson }}

    validation:
      app: {{env "K8S_NAMESPACE_VALIDATION_APP" | default "^[a-zA-Z0-9][-a-zA-Z0-9]{2,}$" | toJson }}
      team: {{env "K8S_NAMESPACE_VALIDATION_TEAM" | default "^[a-zA-Z0-9]{3,}$" | toJson }}

    annotations:
      description: {{env "K8S_ANNOTATION_NAMESPACE_DESCRIPTION" | default "stable.webdevops.io/description" | toJson }}
      immortal: {{env "K8S_ANNOTATION_NAMESPACE_IMMORTAL" | default "stable.webdevops.io/immortal" | toJson }}
      networkPolicy: {{env "K8S_ANNOTATION_NAMESPACE_NETWORKPOLICY" | default "stable.webdevops.io/networkPolicy" | toJson }}

    labels:
      name: {{env "K8S_LABEL_NAME" | default "name" | toJson }}
      user: {{env "K8S_LABEL_USER" | default "user" | toJson }}
      team: {{env "K8S_LABEL_TEAM" | default "team" | toJson }}
      environment: {{env "K8S_LABEL_ENV" | default "env" | toJson }}

    role:
      team: {{env "K8S_TEAM_NAMESPACEROLE" | default "admin" | toJson }}
      user: {{env "K8S_USER_NAMESPACEROLE" | default "admin" | toJson }}
      private: {{env "K8S_USER_NAMESPACEROLE_PRIVATE" |default "true" }}

    quota:
      user: {{env "K8S_NAMESPACE_USER_QUOTA" | default "0" | int }}
      team: {{env "K8S_NAMESPACE_TEAM_QUOTA" | default "0" | int }}

    settings: []

    networkPolicy:
      - name: none
        description: No policy (using Cluster defaults)
      - name: allow-all
        description: Allow all traffic
        path: ./config/networkpolicy/allow-all.yaml
      - name: allow-namespace
        description: Allow all same namespace traffic
        path: ./config/networkpolicy/allow-namespace.yaml
      - name: allow-cluster
        description: Allow all cluster traffic
        path: ./config/networkpolicy/allow-cluster.yaml
      - name: deny-all
        description: Deny all traffic
        path: ./config/networkpolicy/deny-all.yaml
        default: true

permissions:
  default:
    teams: []

  user: {}
  group: {}
  team: {}

alertmanager: {}
