application:
  session:
    type: {{env "SESSION_TYPE" | default "internal" | toJson }}
    expiry: {{env "SESSION_EXPIRY" | default "168h" | toJson }}

    cookieName: {{env "SESSION_COOKIE_NAME" | default "console-sess" | toJson }}

    internal: {}

    secureCookie:
      hashKey: {{env "SESSION_SECURECOOKIE_HASHKEY" | default "F11JJT1PWFfcPbcnltjMeiFSEZOt3F3I" | toJson }}
      blockKey: {{env "SESSION_SECURECOOKIE_BLOCKKEY" | default "XDC0RgG55pPRQLb!" | toJson }}

    redis:
      addr: {{env "SESSION_REDIS_ADDR" | toJson }}
      timeout: {{env "SESSION_REDIS_TIMEOUT"  | default "10s" | toJson }}
      maxActive: {{env "SESSION_REDIS_MAXACTIVE"  | default "10" | int }}
      password: {{env "SESSION_REDIS_PASSWORD"  | default "" | toJson }}
      database: {{env "SESSION_REDIS_DATABASE"  | default "" | toJson }}
      prefix: {{env "SESSION_REDIS_PREFIX"  | default "" | toJson }}
      delim:  {{env "SESSION_REDIS_DELIM"  | default "|" | toJson }}

  oauth:
    provider: {{env "OAUTH_PROVIDER" | toJson }}
    usernamePrefix: {{env "OAUTH_USERNAME_PREFIX" | toJson }}
    groupPrefix: {{env "OAUTH_GROUPS_PREFIX" | default "oidc:"  | toJson }}
    redirectUrl: {{env "OAUTH_REDIRECT_URL" | default "oidc:" | toJson }}

    azuread:
      tenant: {{env "OAUTH_AZUREAD_TENANT" | toJson }}
      clientId: {{env "OAUTH_CLIENT_ID" | toJson }}
      clientSecret: {{env "OAUTH_CLIENT_SECRET" | toJson }}

      endpointAuth: {{env "OAUTH_ENDPOINT_AUTH" | toJson }}
      endpointToken: {{env "OAUTH_ENDPOINT_TOKEN" | toJson }}

    filter:
      usernameWhitelist: {{env "OAUTH_USERNAME_FILTER_WHITELIST" | toJson }}
      usernameBlacklist: {{env "OAUTH_USERNAME_FILTER_BLACKLIST" | toJson }}

  notification:
    slack:
      webhook: {{env "NOTIFICATION_SLACK_WEBHOOK" | toJson }}
      channel: {{env "NOTIFICATION_SLACK_CHANNEL" | toJson }}
      message: {{env "NOTIFICATION_SLACK_MESSAGE" | default "%s: %s" | toJson }}

  kubernetes:
    objectsPath: ./config/kubernetes

    environments: []

    namespace:
      filter:
        access: {{env "K8S_NAMESPACE_ACCESS_FILTER" | default "^(dev|test|int|isa|load|play|prod|team|user)\\-([a-zA-Z0-9]+\\-[a-zA-Z0-9]+|[a-zA-Z0-9]+)$" | toJson }}
        delete: {{env "K8S_NAMESPACE_DELETE_FILTER" | default "^(team|user)\\-.*$" | toJson }}
        user: {{env "K8S_NAMESPACE_USER_FILTER" | default "^user\\-%s\\-" | toJson }}
        team: {{env "K8S_NAMESPACE_TEAM_FILTER" | default "^team\\-%s\\-" | toJson }}

      validation:
        app: {{env "K8S_NAMESPACE_VALIDATION_APP" | default "^[a-zA-Z0-9][-a-zA-Z0-9]{2,}$" | toJson }}
        team: {{env "K8S_NAMESPACE_VALIDATION_TEAM" | default "^[a-zA-Z0-9]{3,}$" | toJson }}

      annotations:
        description: {{env "K8S_ANNOTATION_NAMESPACE_DESCRIPTION" | default "stable.webdevops.io/description" | toJson }}
        immortal: {{env "K8S_ANNOTATION_NAMESPACE_IMMORTAL" | default "stable.webdevops.io/immortal" | toJson }}
        netpol: {{env "K8S_ANNOTATION_NAMESPACE_NETPOL" | default "stable.webdevops.io/netpol" | toJson }}

      labels:
        name: {{env "K8S_LABEL_NAME" | default "name" | toJson }}
        user: {{env "K8S_LABEL_USER" | default "user" | toJson }}
        team: {{env "K8S_LABEL_TEAM" | default "team" | toJson }}
        environment: {{env "K8S_LABEL_ENV" | default "env" | toJson }}

      role:
        team: {{env "K8S_TEAM_NAMESPACEROLE" | default "admin" | toJson }}
        user: {{env "K8S_USER_NAMESPACEROLE" | default "admin" | toJson }}
        private: {{env "K8S_USER_NAMESPACEROLE_PRIVATE" |default "true" }}

      quota:
        user: {{env "K8S_NAMESPACE_USER_QUOTA" | default "0" | int }}
        team: {{env "K8S_NAMESPACE_TEAM_QUOTA" | default "0" | int }}


settings:
  vault:
    url: {{env "AZURE_VAULT_URL" | toJson }}

  user: []
  team: []

azure:
  resourcegroup:
    validation:
      regexp: "^(.+)-rg$"

    tags: []


kubernetes:
  namespace:
    settings: []

permissions:
  default:
    teams: []

  user: {}
  group: {}
  team: {}

alertmanager: {}
