apiVersion: v1
kind: LimitRange
metadata:
  name: limit
  annotations:
    "helm.sh/resource-policy": keep
spec:
  limits:
    - type: Container
      default:
        memory: 256Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: 100m
      maxLimitRequestRatio:
        memory: 1
        cpu: 100
